# Generated by Django 3.2.7 on 2021-11-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='DEGREE',
        ),
        migrations.RemoveField(
            model_name='user',
            name='NUMBER_OF_INTERNSHIPS',
        ),
        migrations.AddField(
            model_name='user',
            name='MONTHS_INTERNING',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='company_id',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='application',
            name='response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='GPA',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='college',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
