# Generated by Django 3.2.7 on 2021-11-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserGraphPoint',
        ),
    ]
